Create dummy server and base dockerfile with dependencies
ForkMyLife-Clinic-2023/Magic pull request #16
Opened 2023-10-07 15:45 UTC by HanBinGer

2023-10-07 15:49 UTC, mohorka commented
Предлагаю добавить в readme инструкцию по запуску, пока что можно по сборке и запуску контейнера

2023-10-07 16:04 UTC, mohorka requested changes

2023-10-07 16:04 UTC, mohorka commented on magic/main.py
> +from fastapi import FastAPI
прогони пожалуйста flake8 на этом файле, как минимум нет отступа после импортов

2023-10-07 16:04 UTC, mohorka commented on magic/main.py
> +class Prompt(BaseModel):
Добавь пожалуйста докстрингу

2023-10-17 19:13 UTC, mohorka requested changes

2023-10-17 19:13 UTC, mohorka commented on magic/main.py
> +app = FastAPI()
Договорились, что пишем бэк сразу на тг-шном фрейме, придется переделать dummy метод

2023-10-18 12:43 UTC, HanBinGer commented on magic/main.py
> +from fastapi import FastAPI
переписал на tg API и поправил замечания

2023-10-18 12:45 UTC, HanBinGer commented on magic/main.py
> +app = FastAPI()
переделал на тг

2023-10-23 10:05 UTC, mohorka commented
Добавь пожалуйста описание для PR

2023-10-23 10:10 UTC, mohorka requested changes

2023-10-23 10:10 UTC, mohorka commented on dockerfile
> +ENV BOT_TOKEN=6659670636:AAFPGljPDglDRV2pI2wCI3Zg1YxLMxyMmEM
Плохо хардкодить ключи в докерфайле. Предлагаю заменить ENV на ARG и передавать этот параметр аргументом при сборке (см флаг build-arg в документации docker build)

2023-10-23 10:10 UTC, mohorka commented on dockerfile
> +CMD ["python", "magic/main.py"]
Предлагаю пока что убрать cmd с запуском файла, так как текущая версия контейнера скорее про разработку, чем про рантайм.

2023-10-23 10:10 UTC, mohorka commented on magic/main.py
> +    This handler receives messages with `/start` command
Поменяй пожалуйста здесь и далее докстринги в соответствии со стайлгайдом

2023-10-23 10:10 UTC, mohorka commented on magic/main.py
> +        # Send a copy of the received message
Данный комментарий не несет полезной нагрузки, поскольку из кода можно и так понять, что происходит, убери его, пожалуйста

2023-10-23 10:10 UTC, mohorka commented on magic/main.py
> +        # But not all the types is supported to be copied so need to handle it
Аналогично, никакой полезной смысловой нагрузки

2023-10-23 10:10 UTC, mohorka commented on magic/main.py
> +    # Initialize Bot instance with a default parse mode which will be passed
Аналогично, никакой полезной смысловой нагрузки

2023-10-23 10:10 UTC, mohorka commented on magic/main.py
> +    # And the run events dispatching
Снова бессмысленный комментарий, см. стайлгайд

2023-10-23 13:28 UTC, mohorka commented
И давай дальше в соответсвии с стайлгайдом называть коммиты и по возможности переименуй ветку, пожалуйста

2023-10-23 16:13 UTC, HanBinGer commented on dockerfile
> +ENV BOT_TOKEN=6659670636:AAFPGljPDglDRV2pI2wCI3Zg1YxLMxyMmEM
Убрал дефолтный ключ

2023-10-23 16:13 UTC, HanBinGer commented on dockerfile
> +CMD ["python", "magic/main.py"]
done

2023-10-23 16:13 UTC, HanBinGer commented on magic/main.py
> +    This handler receives messages with `/start` command
done

2023-10-23 16:13 UTC, HanBinGer commented on magic/main.py
> +        # Send a copy of the received message
done

2023-10-23 16:13 UTC, HanBinGer commented on magic/main.py
> +        # But not all the types is supported to be copied so need to handle it
done

2023-10-23 16:13 UTC, HanBinGer commented on magic/main.py
> +    # Initialize Bot instance with a default parse mode which will be passed
done

2023-10-26 08:32 UTC, mohorka approved these changes

2023-10-26 08:32 UTC, mohorka approved these changes

2023-10-26 08:33 UTC, mohorka approved these changes

2023-10-26 08:37 UTC, merged